package mc.com.beans;
// Generated 15 nov. 2018 09:40:55 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "documents")
public class Document implements java.io.Serializable {	
	private static final long serialVersionUID = 10000L;
	private int id;
	private Post post;
	private String name;
	private String filename;
	private String url;
	private String type;

	
	public Document() {
	}

	public Document(String name, String filename) {
		this.name = name;
		this.filename=filename;
	}

	public Document(int id, Post post, String name, String filename, String url) {
		this.id = id;
		this.post = post;
		this.name = name;
		this.filename = filename;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PostId")
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "Name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Filename", length = 200)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "Url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	@Column(name = "Type", length = 5)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
