package mc.com.beans;
// Generated 15 nov. 2018 09:40:55 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects")
public class Project implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int id;
	private Category category;
	private Post post;
	private String title;
	private String filename;
	private String url;
	private Set<ProjectTag> projecttags = new HashSet<ProjectTag>(0);

	public Project() {
	}

	public Project(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public Project(int id, Category category, Post post, String title, String filename, String url,	Set<ProjectTag> projecttags) {
		this.id = id;
		this.category = category;
		this.post = post;
		this.title = title;
		this.filename = filename;
		this.url = url;
		this.projecttags = projecttags;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryId")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PostId")
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "Title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Filename", length = 50)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "Url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<ProjectTag> getProjectTags() {
		return this.projecttags;
	}

	public void setProjectTags(Set<ProjectTag> projecttags) {
		this.projecttags = projecttags;
	}

}
