package mc.com.beans;
// Generated 15 nov. 2018 09:40:55 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Projecttag generated by hbm2java
 */
@Entity
@Table(name = "projecttags")
public class ProjectTag implements java.io.Serializable {

	private int id;
	private Project project;
	private Tag tag;

	public ProjectTag() {
	}

	public ProjectTag(int id) {
		this.id = id;
	}

	public ProjectTag(int id, Project project, Tag tag) {
		this.id = id;
		this.project = project;
		this.tag = tag;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjectId")
	public Project getproject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TagId")
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
