package mc.com;
// Generated 13 nov. 2018 10:20:54 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts")
public class Posts implements java.io.Serializable {

	private int id;
	private Categories categories;
	private String title;
	private Date date;
	private String description;
	private String file;
	private Set<PostTag> postTags = new HashSet<PostTag>(0);

	public Posts() {
	}

	public Posts(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public Posts(int id, Categories categories, String title, Date date, String description, String file,
			Set<PostTag> postTags) {
		this.id = id;
		this.categories = categories;
		this.title = title;
		this.date = date;
		this.description = description;
		this.file = file;
		this.postTags = postTags;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "file", length = 65535)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "posts")
	public Set<PostTag> getPostTags() {
		return this.postTags;
	}

	public void setPostTags(Set<PostTag> postTags) {
		this.postTags = postTags;
	}

}
