package mc.com;
// Generated 13 nov. 2018 10:20:54 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags")
public class Tags implements java.io.Serializable {

	private int id;
	private String name;
	private Set<PostTag> postTags = new HashSet<PostTag>(0);

	public Tags() {
	}

	public Tags(int id) {
		this.id = id;
	}

	public Tags(int id, String name, Set<PostTag> postTags) {
		this.id = id;
		this.name = name;
		this.postTags = postTags;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<PostTag> getPostTags() {
		return this.postTags;
	}

	public void setPostTags(Set<PostTag> postTags) {
		this.postTags = postTags;
	}

}
